name = "my-app"
main = "src/index.ts"
compatibility_date = "2024-12-12"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "postgresql://task-facilities_owner:ycK93flBowbH@ep-withered-mountain-a5zls9os.us-east-2.aws.neon.tech/task-facilities?sslmode=require"
BASE_URL = "https://pub-6b268ffe401945af8f7e5ba36f02cc7f.r2.dev"
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1

[[r2_buckets]]
bucket_name = "my-r2-bucket"
binding = "my_r2_bucket"